apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: bookbooker
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: textstore
  namespace: bookbooker
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: textstore
  template:
    metadata:
      labels:
        app: textstore
    spec:
      # cleans up any stale lock files before mongod starts
      initContainers:
        - name: init-unlock
          image: busybox:1.36
          command: ['sh','-c','rm -f /data/db/mongod.lock /data/db/WiredTiger.lock || true']
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      containers:
        - name: mongo
          image: mongo:7
          args: ["--bind_ip_all","--quiet"]
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          readinessProbe:
            tcpSocket: { port: 27017 }
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 12
          livenessProbe:
            tcpSocket: { port: 27017 }
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: textstore
  namespace: bookbooker
spec:
  selector:
    app: textstore
  ports:
    - port: 27017
      targetPort: 27017
