apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: bookbooker
spec:
  replicas: 2
  selector: { matchLabels: { app: worker } }
  template:
    metadata: { labels: { app: worker } }
    spec:
      containers:
        - name: worker
          image: jackspawwow/bb-worker:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
            - name: OPENLIB
              value: "1"
          ports: [{ containerPort: 3000 }]
          readinessProbe:
            httpGet: { path: /healthz, port: 3000 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 3000 }
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: bookbooker
spec:
  selector: { app: worker }
  ports:
    - port: 3000
      targetPort: 3000
