apiVersion: v1
kind: Service
metadata:
  name: meta
  namespace: bookbooker
  labels:
    app: meta
spec:
  selector:
    app: meta
  ports:
    - port: 3001
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meta
  namespace: bookbooker
  labels:
    app: meta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meta
  template:
    metadata:
      labels:
        app: meta
    spec:
      containers:
        - name: meta
          image: jackspawwow/bb-meta:v1   # or v2 if you pushed it
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: production
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3001
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
