apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: bookbooker
  labels:
    app: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: bookbooker
  labels:
    app: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: jackspawwow/bb-gateway:v1   # or v2 if you pushed it
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: WORKER_HOST
              value: worker
            - name: META_HOST
              value: meta
            - name: MONGO_URI
              value: mongodb://textstore:27017/bookbooker
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
